export const RecommendationsContext = [
  {
    desc: "A chic brown midi dress with a structured fit and a statement belt for a polished look.",
    name: "Belted Brown Midi Dress",
    price: 104.99,
    category: "dresses",
    image_url: "/catalog/brown_midi_dress.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A breezy yellow printed dress with a smocked top, perfect for sunny days.",
    name: "Yellow Printed Midi Dress",
    price: 97.5,
    category: "dresses",
    image_url: "/catalog/yellow_midi_dress.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "An off-shoulder floral dress featuring a colorful, artistic print and flowy silhouette.",
    name: "Floral Off-Shoulder Dress",
    price: 108.25,
    category: "dresses",
    image_url: "/catalog/painted_dress.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A sleeveless beige wrap dress with contrasting trim and a textured waist belt for a tailored fit.",
    name: "Beige Wrap Midi Dress",
    price: 102.3,
    category: "dresses",
    image_url: "/catalog/white_madi_dress.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A fitted olive green midi dress with ruching and an elegant shoulder brooch.",
    name: "Ruched Olive Midi Dress",
    price: 106.9,
    category: "dresses",
    image_url: "/catalog/green_dress.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A sleek red satin slip dress with a minimalist silhouette and delicate straps.",
    name: "Red Satin Slip Dress",
    price: 99.8,
    category: "dresses",
    image_url: "/catalog/red_satin_dress.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A deep burgundy dress with draped details and a metallic pin accent on the shoulder.",
    name: "Burgundy Draped Dress",
    price: 109.2,
    category: "dresses",
    image_url: "/catalog/red_dress.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A white midi dress with a structured bodice and wide straps for an elegant summer look.",
    name: "White Structured Midi Dress",
    price: 100.6,
    category: "dresses",
    image_url: "/catalog/white_maxi_dress.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A crisp white button-up jumpsuit with wide legs and a flattering waist belt.",
    name: "White Belted Jumpsuit",
    price: 84.75,
    category: "dresses",
    image_url: "/catalog/white_jumpsuit.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A pair of off-white wide-leg trousers crafted from breathable fabric for all-day comfort.",
    name: "White Wide-Leg Trousers",
    price: 92.6,
    category: "lower_body",
    image_url: "/catalog/white_wide_pants.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A slate blue ruched bodycon dress with a single-shoulder neckline and gold-tone shell embellishment.",
    name: "One-Shoulder Ruched Dress",
    price: 107.95,
    category: "dresses",
    image_url: "/catalog/seashell_dress.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Tailored sage green Bermuda shorts with a suede-effect belt for a refined summer look.",
    name: "Belted Pleated Shorts",
    price: 86.4,
    category: "lower_body",
    image_url: "/catalog/green_shorts.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Knitted drawstring pants in a deep green plaid with a soft, cozy feel and elastic waistband.",
    name: "Green Knit Plaid Pants",
    price: 89.5,
    category: "lower_body",
    image_url: "/catalog/green_pants.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Relaxed-fit tie-dye inspired velour pants in warm red tones, ideal for cozy styling.",
    name: "Red Swirl Velour Pants",
    price: 90.8,
    category: "lower_body",
    image_url: "/catalog/red_pants.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Classic white sweatpants in a breathable cotton blend with adjustable drawstring waist.",
    name: "White Drawstring Sweatpants",
    price: 85.99,
    category: "lower_body",
    image_url: "/catalog/sweats_white.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Minimalist black shorts with an elasticated waist and textured finish for everyday comfort.",
    name: "Black Textured Knit Shorts",
    price: 83.45,
    category: "lower_body",
    image_url: "/catalog/shorts.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Light yellow button-up shirt with a crisp collar and subtle structure, perfect for layering or standalone wear.",
    name: "Soft Yellow Button-Up Shirt",
    price: 78.2,
    category: "upper_body",
    image_url: "/catalog/yellow_button.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Elegant white wide-leg trousers with tailored seams and a clean, minimalist silhouette.",
    name: "White Tailored Trousers",
    price: 94.1,
    category: "lower_body",
    image_url: "/catalog/white_pants.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Classic light-wash jeans with a high waist and relaxed straight-leg cut for casual comfort.",
    name: "Washed Gray Straight Jeans",
    price: 91.35,
    category: "lower_body",
    image_url: "/catalog/gray_jeans.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A bold short-sleeve shirt featuring vertical black and white stripes, perfect for a crisp summer look.",
    name: "Vertical Stripe Short-Sleeve Shirt",
    price: 69.5,
    category: "upper_body",
    image_url: "/catalog/stripe_shirt.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Short-sleeve floral shirt in muted olive tones with a soft, breezy linen blend and chest pocket.",
    name: "Olive Floral Camp Collar Shirt",
    price: 74.99,
    category: "upper_body",
    image_url: "/catalog/floral_shirt.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Classic oversized white tee made from breathable cotton, ideal for layering or solo wear.",
    name: "Basic White Oversized T-Shirt",
    price: 65.0,
    category: "upper_body",
    image_url: "/catalog/white_shirt.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A sleek navy blue knit polo shirt with a clean three-button collar and soft texture.",
    name: "Navy Knit Polo Shirt",
    price: 72.3,
    category: "upper_body",
    image_url: "/catalog/polo_shirt.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Light-wash denim jeans with a relaxed fit and high-rise waist for laid-back everyday wear.",
    name: "Light Blue Relaxed Jeans",
    price: 88.25,
    category: "lower_body",
    image_url: "/catalog/jeans.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A deep navy blue button-up shirt with a structured collar and chest pocket for everyday smart-casual wear.",
    name: "Dark Navy Cotton Shirt",
    price: 81.9,
    category: "upper_body",
    image_url: "/catalog/button_shirt.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Refined beige linen blazer with notched lapels and flap pockets—perfect for summer formal wear.",
    name: "Beige Linen Blazer",
    price: 85.0,
    category: "upper_body",
    image_url: "/catalog/blazer.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Slim-fit black trousers made from breathable fabric for elevated comfort and style.",
    name: "Black Lightweight Trousers",
    price: 93.7,
    category: "lower_body",
    image_url: "/catalog/black_pants.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Short-sleeve button-up shirt in pure white linen with a relaxed drape and summer-ready cut.",
    name: "White Linen Open-Collar Shirt",
    price: 80.4,
    category: "upper_body",
    image_url: "/catalog/linen_shirt.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "Tailored-fit pants crafted from breathable beige linen for an airy, elevated summer outfit.",
    name: "Beige Linen Slim Pants",
    price: 90.45,
    category: "lower_body",
    image_url: "/catalog/linen_pants.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
  {
    desc: "A textured short-sleeve shirt featuring a vertical woven pattern in neutral and blue tones, perfect for layering or wearing on its own.",
    name: "Textured Woven Pattern Shirt",
    price: 79.9,
    category: "upper_body",
    image_url: "/catalog/textured_shirt.jpg",
    sizes_available: ["XS", "S", "M", "L", "XL"],
  },
];
